### ISSUE TITLE
Drop/Modify Anchors

### ISSUE THREAD

**Issue by reergymerej** [aleclarson/glob-regex#2]
I'd like to use this to without the anchors, or at least `^`.  Is there a way to do that?  Thanks!

**Example**

 I want this to evaluate to `true`, but it's not because of the `^` anchor. `․/^([^\/]+)\.js$/`
```js
globRegex("*.js").test("./src/x/y/z.js")
```

**Comment by aleclarson** [comment]
Is there a reason `globRegex("**/*.js")` won't work for your use case?

If you're processing user input (ie: CLI tool), you can do `userInput.replace(/^\*\./, "**/*.")` if you want.

**Comment by reergymerej** [comment]
I assume your version is closer to the proper glob usage than the informal version I want to support.  I'll look at adding an intermediate step to bridge from the user to glob-regex.  Thanks for the suggestion!
